"""Add deactivated at for soft delete user

Revision ID: 006d5e137b8a
Revises: 9221fd988e1b
Create Date: 2026-09-13 11:37:44.754239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006d5e137b8a'
down_revision = '9221fd988e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')

    # ### end Alembic commands ###
