"""Init db migration

Revision ID: 2b063bba0f81
Revises: 
Create Date: 2026-09-11 09:37:50.502979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b063bba0f81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_progress',
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('upload_id')
    )
    with op.batch_alter_table('upload_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_progress_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_progress_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_progress_status'))
        batch_op.drop_index(batch_op.f('ix_upload_progress_created_at'))

    op.drop_table('upload_progress')
    # ### end Alembic commands ###
